### ISSUE TITLE
Docker host can't access image

### ISSUE THREAD

**Issue by daithi-coombes** [paritytech/parity#5522]
I'm having issues getting the Docker image to be accessed by the host machine. It appears that parity is binding to the container's localhost (127.0.01) instead of 0.0.0.0. I'm not sure if changing this is a security issue? For me it seems like a bug for access to the web-wallet.

Here is the docker-compose file I'm trying to get working...

```yml
version: "3"

services:

  web:
    build: .
    ports:
      - "8081:8080"
    links:
      - parity

  parity:
      image: "ethcore/parity:nightly"
      ports:
        - "8080:8080"
        - "8545:8545"
```
