### ISSUE TITLE
Feature Request: Interface for Parity Snap

### ISSUE THREAD

**Issue by jbentke** [paritytech/parity#5953]
I used your Snap release, which works fine by the way, but without an interface I can not reach it with another snap. Are you guys working on an interface for snapd so that the Snap can (really) be used in Ubuntu Core? (and are you going to push it to the Store?)

**Comment by rphmeier** [comment]
@elopio can probably answer this as he's done most of the work on snap packaging so far

**Comment by elopio** [comment]
Hello @jbentke. The idea of putting the snap in the edge channel is to get feedback, so thanks a lot for your message.

It's not clear for me what you are trying to do. The parity snap can be executed in Ubuntu Core without problems right now. And it has the network interfaces, so you can access the JSONRPC API through HTTP: https://github.com/paritytech/parity/wiki/JSONRPC

And it is in the store, but only in the edge channel for now.

**Comment by jbentke** [comment]
Thanks for the feedback. Maybe I got the whole thing wrong, but I wrote a simple snap that prints out the Blocknumber.
```javascript
var Web3 = require("web3")
var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"))
var number = web3.eth.blockNumber
console.log(number)
```
I snap that code with the nodes plugin and add the network plugs so it looks like this:

```
name: demo
version: '0.0.1'
summary: prints out the block number
description: |
  simple web3 snap demo. requires running Ethereum client
grade: devel 
confinement: devmode 

apps:
   demo:
     command: bin/demo
     plugs: [network, network-bind]

parts:
   demo:
      source: .
      plugin: nodejs 
      node-packages: [web3]
```
I started the parity snap with `parity &>/dev/null &`. Then I install my snap in devmode and everything works fine. But when I install my snap with strict confinement it does not find the localhost. Thats why I thought there needs to be an extra Interface for RPCs?

**Comment by elopio** [comment]
@jbentke sorry for the long time to reply. I had some time to dig into this, and actually found something interesting. I had to slightly change your files to package them:

demo.js:
```#!/usr/bin/env node

const Web3 = require("web3")
var web3 = new Web3()
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'))
var number = web3.eth.blockNumber
console.log(number)
```

package.json:

```
{
    "name": "demo",
    "version": "0.0.1",
    "description": "print out blocknumber",
    "bin": "./demo.js",
    "dependencies": {
        "web3": "0.20.1"
    }
}
```

snapcraft.yaml:
```
name: demo
version: '0.0.1'
summary: prints out the block number
description: |
  simple web3 snap demo. requires running Ethereum client
grade: devel
confinement: strict

apps:
   demo:
     command: bin/demo
     plugs: [home, network, network-bind]

parts:
   demo:
      source: .
      plugin: nodejs
```

Put that into an empty workspace dir. Then, make and install the snap:

$ snapcraft
$ sudo snap install *.snap --dangerous
$ cd ~/snap/demo/current
$ demo

This works, but the `cd ~/snap/demo/current` is very important. That is a directory that's writable by the snap. If you try to run it from `~`, this error ends up in the syslog:

`Jul 21 20:58:40 juju-44eb60-remote-devel-0 kernel: [6664707.185484] audit: type=1400 audit(1500670720.035:8905): apparmor="DENIED" operation="mknod" profile="snap.demo.demo" name="/home/ubuntu/.node-xmlhttprequest-sync-25928" pid=25928 comm="node" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000`

So, the problem is that your script is trying to write a file `.node-xmlhttprequest-sync-25928` in the current directory. If the current is not writable by the snap, it will fail.

That kind of directories are usually controlled by environment variables. But I don't know much about nodejs, nor web3. Does that ring a bell for any of you?
