### ISSUE TITLE
Running parity with docker-compose leads to connection refused

### ISSUE THREAD

**Issue by ThomasMeier** [paritytech/parity#6879]
Expected: Able to access `http://localhost:8180`
Action: Connection refused

Not accessible at `127.0.0.1:8180` or `<docker ip>:8180` or `0.0.0.0:8180` either.

### System

Parity v1.8.1
Archlinux
Installed with Docker
Start up with docker-compose.yml

### Compose File(s) Used

```yml
version: "3"
services:
  eth:
    image: parity/parity:v1.8.1
    ports:
      - "8545:8545"
      - "8180:8180"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - "/home/me/.parity:/root/.local/share/io.parity.ethereum"
    command: --chain ropsten --base-path /root/.local/share/io.parity.ethereum/
```

Also tried:

```yml
version: "3"
services:
  eth:
    image: parity/parity:v1.8.1
    ports:
      - "8545:8545"
      - "127.0.0.1:8180:8180"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - "/home/me/.parity:/root/.local/share/io.parity.ethereum"
    command: --chain ropsten --base-path /root/.local/share/io.parity.ethereum/  --dapps-interface all --dapps-hosts all
```

```yml
version: "3"
services:
  eth:
    image: parity/parity:v1.8.1
    ports:
      - "8545:8545"
      - "127.0.0.1:8180:8180"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - "/home/me/.parity:/root/.local/share/io.parity.ethereum"
    command: --chain ropsten --base-path /root/.local/share/io.parity.ethereum/  --jsonrpc-interface all --jsonrpc-hosts all
```
These all run fine. `docker attach` shows me that blocks are being imported fine.

#### `docker ps`

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                                                                                        NAMES
f16b3d68f616        parity/parity:v1.8.1   "/parity/parity --..."   About an hour ago   Up 44 seconds       0.0.0.0:8080->8080/tcp, 0.0.0.0:8180->8180/tcp, 0.0.0.0:8545-8546->8545-8546/tcp, 0.0.0.0:30303->30303/tcp   parity_eth_1
```

#### `netstat -penaut`

```
tcp6       0      0 :::8080                 :::*                    LISTEN      0          1305216    17362/docker-proxy  
tcp6       0      0 :::8180                 :::*                    LISTEN      0          1305204    17351/docker-proxy  
tcp6       0      0 :::30303                :::*                    LISTEN      0          1305186    17316/docker-proxy  
tcp6       0      0 :::8545                 :::*                    LISTEN      0          1304193    17340/docker-proxy      
tcp6       0      0 :::8546                 :::*                    LISTEN      0          1301410    17328/docker-proxy 
```

**Comment by Office-Julia** [comment]
Hello. Let me assist you with your issue.

Your Docker configuration looks good at first glance and matching Docker documentation.

At first place, please note Parity version 1.8.1 is still Beta, have you tried launch our latest stable release 1.7.8 instead? (https://github.com/paritytech/parity/releases)

Could you please answer the following questions as well?
1. Are you using any kind of firewall?
2. What operation system you are running Parity on? (operating system of your machine, not Docker container)
3. What flags are you running Parity with? (if any)
4. Do you use any config file?
5. Please provide your Parity logs for our inspection

Regards,
Julia.

**Comment by 5chdn** [comment]
Does it work if you add `--unsafe-expose` to the `command:`?

You will probably want to expose web sockets and user interface hosts/interface and not only json rpc or dapps.

**Comment by BransonGitomeh** [comment]
hey, can you provide the propper docker compose entry that will expose all this ports? im also facing this issue where i get errors that it cant `connection not open on send()`

my docker-compose entry is
```
  parity:
    image: parity/parity:v1.7.0
    command: --chain kovan --unsafe-expose
    ports:
      - "8180:8180"
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
```
