### ISSUE TITLE
Tendermint: no blocks generated

### ISSUE THREAD

**Issue by bgrieder** [paritytech/parity#8157]
> I'm running:
>
> - **Which Parity version?**: v1.9.4-beta-6f21a32-20180228/x86_64-macos/rustc1.24.0
> - **Which operating system?**: MacOS
> - **How installed?**: via installer binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: custom
> - **Did you try to restart the node?**: yes

This setup of 3 validator nodes work fine with Authority Round (blocks are generated) but does not work with Tendermint (validators see each other but no blocks are generated). The  general guidelines of https://wiki.parity.io/Demo-PoA-tutorial.html have been followed.

From the working set-up for Aura,  the `engine` entry of genesis.json was replaced:

**Original (Aura)**

    "engine": {
        "authorityRound": {
            "params": {
                "stepDuration": "3",
                "validators": {
                    "list": [
                        "0x527c6d143a090e9c1c18ae31bb05c717ca94e915",
                        "0x0072873e3b02747171e033470f94f5b8fd1ed053",
                        "0x005c381e1971b7eff421f2b8553fc542ad78097f"
                    ]
                }
            }
        }
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x5B8D80"
    },

**Tendermint**

        "engine": {
            "tendermint": {
                "params": {
                    "validators": {
                        "list": [
                            "0x527c6d143a090e9c1c18ae31bb05c717ca94e915",
                            "0x0072873e3b02747171e033470f94f5b8fd1ed053",
                            "0x005c381e1971b7eff421f2b8553fc542ad78097f"
                        ]
                    }
                }
            }
        },
        "genesis": {
            "seal": {
                "tendermint": {
                    "round": "0x0",
                    "proposal": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                    "precommits": [
                        "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
                    ]
                }
            },
            "difficulty": "0x20000",
            "gasLimit": "0x5B8D80"
        },

**Comment by ordian** [comment]
I was able to reproduce the issue [here](https://github.com/ordian/parity-issue8157) with the panic at the end:
```
Thread 'IO Worker #1' panicked at 'Invalid header.: RlpIsTooShort'
```
Trying to dig deeper.

**Comment by roynalnaruto** [comment]
@bgrieder Hi, I am trying to do a similar setup (using docker containers [ref](https://github.com/orbita-center/parity-poa-playground)). Even for me, the blocks are not being mined. Have you found the reason? My `tendermint-config` file looks like : 
```
{
  "name": "parity-tendermint",
  "engine": {
    "tendermint": {
      "params": {
        "validators": {
          "list": [
            "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e",
            "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2",
            "0x002e28950558fbede1a9675cb113f0bd20912019",
	    "0x48f76dac1eb79528ec927ce7d429aef512a21a7c"
          ]
        }
      }
    }
  },
  "params": {
    "maximumExtraDataSize": "0x20",
    "minGasLimit": "0x1388",
    "networkID": "0x2323",
    "gasLimitBoundDivisor": "0x400"
  },
  "genesis": {
    "seal": {
      "tendermint": {
        "round": "0x0",
        "proposal": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
	"precommits": [
	  "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	]
      }
    },
    "difficulty": "0x20000",
    "gasLimit": "0x2fefd8"
  },
  "accounts": {
    ...
  }
}
```

I am getting this log in the still running authority/validator:
```
2018-04-20 03:27:00 UTC    6/25 peers      8 KiB chain   15 KiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-04-20 03:27:30 UTC    6/25 peers      8 KiB chain   15 KiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-04-20 03:27:42 UTC Stage 4 block verification failed for #1 (a672…fbea)
Error: Engine(NotAuthorized(66ae460c87cca597b3b8fee210b07cad7b9a448d))
```

Also, one container failed and stopped due to this error:
```
====================

stack backtrace:
   0:     0x55c747d8bb1c - <no info>
   1:     0x55c747d8b1c2 - <no info>
   2:     0x55c747286725 - <no info>

Thread 'IO Worker #1' panicked at 'Invalid header.: RlpIsTooShort', /checkout/src/libcore/result.rs:916
```

What is wrong?

**Comment by ordian** [comment]
@roynalnaruto the panic was fixed in #8367 (not yet in stable), however the parity's tendermint engine is still not ready for production use. 

The error you're getting (`Engine(NotAuthorized(...))`) is different though, make sure you have [engine_signer](https://github.com/ordian/parity-issue8157/blob/3562cead4bb4b497751e9898f635d86b129d03fc/config/node01.toml#L15-L17) in your node config (see [demo poa tutorial](https://wiki.parity.io/Demo-PoA-tutorial.html)).

**Comment by roynalnaruto** [comment]
@ordian I had used `--engine-signer` while launching the docker container. What is the id in the brackets of the above error `66ae460c87cca597b3b8fee210b07cad7b9a448d`? Because, that is not the public address of any of the 4 validators that I am using. Below is the `docker-compose.yml` I am using:
```
version: '2.1'
services:
  authority0:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority.toml
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
    volumes:
      - ./parity/config:/parity/config:ro
      - authority0:/root/.local/share/io.parity.ethereum/
      - ./parity/authorities/authority0.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}/authority.json:ro
      - ./parity/keys:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}
      - ./parity/authorities/authority0.pwd:/parity/authority.pwd:ro
      - ./parity/node0.network.key:/root/.local/share/io.parity.ethereum/network/key:ro
    ports:
      - 8545:8545
    networks:
      app_net:
        ipv4_address: 172.16.0.10


  authority1:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority.toml
      --engine-signer 0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2
    volumes:
      - ./parity/config:/parity/config:ro
      - authority1:/root/.local/share/io.parity.ethereum/
      - ./parity/authorities/authority1.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}/authority.json:ro
      - ./parity/authorities/authority1.pwd:/parity/authority.pwd:ro
      - ./parity/node1.network.key:/root/.local/share/io.parity.ethereum/network/key:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.11

...

volumes:
  authority0:
  authority1:
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.1/24
        gateway: 172.16.0.1
```

Is there something else wrong?
