### ISSUE TITLE
Thread '<unnamed>' panicked at 'other was less than the current instant'

### ISSUE THREAD

**Issue by KYawn** [paritytech/parity#8720]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.9.5
> - **Which operating system?**: Linux
> - **How installed?**: via Docker
> - **Are you fully synchronized?**: yes(Private Chain)
> - **Which network are you connected to?**: Private chain
> - **Did you try to restart the node?**: Yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**expected behavior**: running stably.
**actual**: It will stop unexpectedly after running serval hours.

====================
host2        |
host2        | stack backtrace:
host2        |    0:     0x555f71458b1c - <no info>
host2        |    1:     0x555f714581c2 - <no info>
host2        |    2:     0x555f70953725 - <no info>
host2        |
host2        | Thread '<unnamed>' panicked at 'other was less than the current instant', /checkout/src/libstd/sys/unix/time.rs:292
host2        |
host2        | This is a bug. Please report it at:
host2        |
host2        |     https://github.com/paritytech/parity/issues/new

**Comment by KYawn** [comment]
**steps to reproduce**: Just running the parity, and wait for serval hours.

And here is my Docker-compose file.
```
version: '3.0'
services:
    host1:
    container_name: host2
    ports:
    - 3079:3079
    - 3778:3778
    - 3067:3067
    - 30303:30303/udp
    image: parity/parity:v1.9.5
    networks:
        my-swarm-network:
        ipv4_address: 172.70.1.12
    volumes:
    - ./deployment/chain/spec.json:/parity/spec.json:ro
    - ./deployment/chain/reserved_peers:/parity/reserved_peers:ro
    - ./deployment/1/password:/parity/password:ro
    - ./deployment/1/authority.toml:/parity/authority.toml:ro
    - ./deployment/1/${NETWORK_NAME}:/parity/data/keys/${NETWORK_NAME}
    - ./data/1:/parity/data
    command: --chain /parity/spec.json --config /parity/authority.toml -d /parity/data
  ipfs_host:
     container_name: ipfs_host2
     ports:
     - 4001:4001
     - 8080:8080
     - 5001:5001
     image: ipfs/go-ipfs:latest
     networks:
     - my-swarm-network
     volumes:
     - ./ipfs/staging:/export
     - ./ipfs/data:/data/ipfs
networks:
    my-swarm-network:
    external: true
```
