### ISSUE TITLE
Empty response from server

### ISSUE THREAD

**Issue by 4ntoine** [paritytech/parity#9128]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.10.9-stable
> - **Which operating system?**: MacOS
> - **How installed?**: homebrew + Docker
> - **Are you fully synchronized?**: no (synchronizing)
> - **Which network are you connected to?**: ropsten
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Actual**

Sometimes i get empty response to `web3_clientVersion` request.

**Expected**

I get normal response every time

**Steps to reproduce**

1. create docker-compose.yaml:
```
# ethereum node with parity
  ethereum:
    container_name: app-parity
    build: ./parity
    ports:
      #- "8180:8180"
      - "8545:8545" # HTTP RPC
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ./ethereum-data/keystore:/root/.local/share/io.parity.ethereum/keys/Ropsten:ro
      - ./ethereum-data/.parity:/root/.local/share/io.parity.ethereum/chains/test/
      - ./misc:/misc:ro
    restart: on-failure
    command: --chain ropsten --cache-size ${CACHE_SIZE:-512} --light --reserved-peers /misc/ropstenpeers.txt --jsonrpc-interface "0.0.0.0" --jsonrpc-hosts all --ui-interface all --jsonrpc-apis eth,net,personal,rpc,web3,pubsub --jsonrpc-server-threads 16 --db-compaction ssd --pruning fast --mode active --no-ancient-blocks --tracing off --no-ipc
    healthcheck:
      # $docker inspect app-parity | jq ".[].State.Health"
      test: "/misc/healthcheck-ethereum.sh 127.0.0.1 8545 Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0"
      interval: 30s
      timeout: 3s
      retries: 3
```
2. run container

> docker-compose up ethereum

3. call:

```
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (52) Empty reply from server
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (52) Empty reply from server
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (52) Empty reply from server
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (52) Empty reply from server
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (52) Empty reply from server
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (56) Recv failure: Connection reset by peer
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (56) Recv failure: Connection reset by peer
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (52) Empty reply from server
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (52) Empty reply from server
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity//v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0","id":2}
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (52) Empty reply from server
/tmp asmirnov$curl --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":2}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:8545
curl: (52) Empty reply from server
```
